import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar_O from "@/components/organ/NavBar_O";
import Footer_O from "@/components/organ/Footer_O";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="fa" data-theme="mytheme">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen antialiased font-yekanRegular overflow-x-hidden`}
      >
        <NavBar_O />
        <main className="min-h-screen">{children}</main>
        <Footer_O />
      </body>
    </html>
  );
}
